// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/namenode/namenode.proto

package namenode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data         []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	AbsolutePath string `protobuf:"bytes,2,opt,name=absolutePath,proto3" json:"absolutePath,omitempty"`
}

func (x *PutReq) Reset() {
	*x = PutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReq) ProtoMessage() {}

func (x *PutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReq.ProtoReflect.Descriptor instead.
func (*PutReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *PutReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutReq) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

type PutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbsolutePath string         `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	DataMessage  []*DataMessage `protobuf:"bytes,2,rep,name=DataMessage,proto3" json:"DataMessage,omitempty"`
}

func (x *PutResp) Reset() {
	*x = PutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResp) ProtoMessage() {}

func (x *PutResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResp.ProtoReflect.Descriptor instead.
func (*PutResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *PutResp) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *PutResp) GetDataMessage() []*DataMessage {
	if x != nil {
		return x.DataMessage
	}
	return nil
}

type FindLeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindLeaderReq) Reset() {
	*x = FindLeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLeaderReq) ProtoMessage() {}

func (x *FindLeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLeaderReq.ProtoReflect.Descriptor instead.
func (*FindLeaderReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{2}
}

type FindLeaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *FindLeaderResp) Reset() {
	*x = FindLeaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLeaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLeaderResp) ProtoMessage() {}

func (x *FindLeaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLeaderResp.ProtoReflect.Descriptor instead.
func (*FindLeaderResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{3}
}

func (x *FindLeaderResp) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type JoinClusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Addr          string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	PreviousIndex uint64 `protobuf:"varint,3,opt,name=PreviousIndex,proto3" json:"PreviousIndex,omitempty"`
}

func (x *JoinClusterReq) Reset() {
	*x = JoinClusterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterReq) ProtoMessage() {}

func (x *JoinClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterReq.ProtoReflect.Descriptor instead.
func (*JoinClusterReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{4}
}

func (x *JoinClusterReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinClusterReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *JoinClusterReq) GetPreviousIndex() uint64 {
	if x != nil {
		return x.PreviousIndex
	}
	return 0
}

type JoinClusterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *JoinClusterResp) Reset() {
	*x = JoinClusterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResp) ProtoMessage() {}

func (x *JoinClusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResp.ProtoReflect.Descriptor instead.
func (*JoinClusterResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{5}
}

func (x *JoinClusterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateDataNodeMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string  `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	UsedDisk   uint64  `protobuf:"varint,2,opt,name=UsedDisk,proto3" json:"UsedDisk,omitempty"`
	UsedMem    uint64  `protobuf:"varint,3,opt,name=UsedMem,proto3" json:"UsedMem,omitempty"`
	CpuPercent float32 `protobuf:"fixed32,4,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	TotalMem   uint64  `protobuf:"varint,5,opt,name=TotalMem,proto3" json:"TotalMem,omitempty"`
	TotalDisk  uint64  `protobuf:"varint,6,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
}

func (x *UpdateDataNodeMessageReq) Reset() {
	*x = UpdateDataNodeMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataNodeMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataNodeMessageReq) ProtoMessage() {}

func (x *UpdateDataNodeMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataNodeMessageReq.ProtoReflect.Descriptor instead.
func (*UpdateDataNodeMessageReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDataNodeMessageReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *UpdateDataNodeMessageReq) GetUsedDisk() uint64 {
	if x != nil {
		return x.UsedDisk
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetUsedMem() uint64 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetTotalMem() uint64 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetTotalDisk() uint64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

type UpdateDataNodeMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *UpdateDataNodeMessageResp) Reset() {
	*x = UpdateDataNodeMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataNodeMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataNodeMessageResp) ProtoMessage() {}

func (x *UpdateDataNodeMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataNodeMessageResp.ProtoReflect.Descriptor instead.
func (*UpdateDataNodeMessageResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDataNodeMessageResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterDataNodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string  `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	UsedDisk   uint64  `protobuf:"varint,2,opt,name=UsedDisk,proto3" json:"UsedDisk,omitempty"`
	UsedMem    uint64  `protobuf:"varint,3,opt,name=UsedMem,proto3" json:"UsedMem,omitempty"`
	CpuPercent float32 `protobuf:"fixed32,4,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	TotalMem   uint64  `protobuf:"varint,5,opt,name=TotalMem,proto3" json:"TotalMem,omitempty"`
	TotalDisk  uint64  `protobuf:"varint,6,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
}

func (x *RegisterDataNodeReq) Reset() {
	*x = RegisterDataNodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDataNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataNodeReq) ProtoMessage() {}

func (x *RegisterDataNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataNodeReq.ProtoReflect.Descriptor instead.
func (*RegisterDataNodeReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterDataNodeReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterDataNodeReq) GetUsedDisk() uint64 {
	if x != nil {
		return x.UsedDisk
	}
	return 0
}

func (x *RegisterDataNodeReq) GetUsedMem() uint64 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *RegisterDataNodeReq) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *RegisterDataNodeReq) GetTotalMem() uint64 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *RegisterDataNodeReq) GetTotalDisk() uint64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

type RegisterDataNodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *RegisterDataNodeResp) Reset() {
	*x = RegisterDataNodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDataNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataNodeResp) ProtoMessage() {}

func (x *RegisterDataNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataNodeResp.ProtoReflect.Descriptor instead.
func (*RegisterDataNodeResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterDataNodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartBeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *HeartBeatReq) Reset() {
	*x = HeartBeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatReq) ProtoMessage() {}

func (x *HeartBeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatReq.ProtoReflect.Descriptor instead.
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{10}
}

func (x *HeartBeatReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type HeartBeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *HeartBeatResp) Reset() {
	*x = HeartBeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResp) ProtoMessage() {}

func (x *HeartBeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResp.ProtoReflect.Descriptor instead.
func (*HeartBeatResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{11}
}

func (x *HeartBeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DataMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{12}
}

func (x *DataMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataMessage) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_proto_namenode_namenode_proto protoreflect.FileDescriptor

var file_proto_namenode_namenode_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x22, 0x40, 0x0a, 0x06, 0x50, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x62, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x67, 0x0a, 0x07,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x62, 0x73, 0x6f, 0x6c,
	0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41,
	0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x0b, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x24, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x5a, 0x0a, 0x0e,
	0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x6f, 0x75, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2b, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x64, 0x44, 0x69,
	0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x55, 0x73, 0x65, 0x64, 0x44, 0x69,
	0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x22, 0x35, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xb9, 0x01,
	0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x29, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x32, 0xc1, 0x03,
	0x0a, 0x0f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3e, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x17,
	0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x53, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0a,
	0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x62, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x11, 0x2e, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x6f, 0x2d, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_namenode_namenode_proto_rawDescOnce sync.Once
	file_proto_namenode_namenode_proto_rawDescData = file_proto_namenode_namenode_proto_rawDesc
)

func file_proto_namenode_namenode_proto_rawDescGZIP() []byte {
	file_proto_namenode_namenode_proto_rawDescOnce.Do(func() {
		file_proto_namenode_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_namenode_namenode_proto_rawDescData)
	})
	return file_proto_namenode_namenode_proto_rawDescData
}

var file_proto_namenode_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_namenode_namenode_proto_goTypes = []interface{}{
	(*PutReq)(nil),                    // 0: namenode_.PutReq
	(*PutResp)(nil),                   // 1: namenode_.PutResp
	(*FindLeaderReq)(nil),             // 2: namenode_.FindLeaderReq
	(*FindLeaderResp)(nil),            // 3: namenode_.FindLeaderResp
	(*JoinClusterReq)(nil),            // 4: namenode_.JoinClusterReq
	(*JoinClusterResp)(nil),           // 5: namenode_.JoinClusterResp
	(*UpdateDataNodeMessageReq)(nil),  // 6: namenode_.UpdateDataNodeMessageReq
	(*UpdateDataNodeMessageResp)(nil), // 7: namenode_.UpdateDataNodeMessageResp
	(*RegisterDataNodeReq)(nil),       // 8: namenode_.RegisterDataNodeReq
	(*RegisterDataNodeResp)(nil),      // 9: namenode_.RegisterDataNodeResp
	(*HeartBeatReq)(nil),              // 10: namenode_.HeartBeatReq
	(*HeartBeatResp)(nil),             // 11: namenode_.HeartBeatResp
	(*DataMessage)(nil),               // 12: namenode_.DataMessage
}
var file_proto_namenode_namenode_proto_depIdxs = []int32{
	12, // 0: namenode_.PutResp.DataMessage:type_name -> namenode_.DataMessage
	10, // 1: namenode_.NameNodeService.HeartBeat:input_type -> namenode_.HeartBeatReq
	8,  // 2: namenode_.NameNodeService.RegisterDataNode:input_type -> namenode_.RegisterDataNodeReq
	4,  // 3: namenode_.NameNodeService.JoinCluster:input_type -> namenode_.JoinClusterReq
	2,  // 4: namenode_.NameNodeService.FindLeader:input_type -> namenode_.FindLeaderReq
	6,  // 5: namenode_.NameNodeService.UpdateDataNodeMessage:input_type -> namenode_.UpdateDataNodeMessageReq
	0,  // 6: namenode_.NameNodeService.Put:input_type -> namenode_.PutReq
	11, // 7: namenode_.NameNodeService.HeartBeat:output_type -> namenode_.HeartBeatResp
	9,  // 8: namenode_.NameNodeService.RegisterDataNode:output_type -> namenode_.RegisterDataNodeResp
	5,  // 9: namenode_.NameNodeService.JoinCluster:output_type -> namenode_.JoinClusterResp
	3,  // 10: namenode_.NameNodeService.FindLeader:output_type -> namenode_.FindLeaderResp
	7,  // 11: namenode_.NameNodeService.UpdateDataNodeMessage:output_type -> namenode_.UpdateDataNodeMessageResp
	1,  // 12: namenode_.NameNodeService.Put:output_type -> namenode_.PutResp
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_namenode_namenode_proto_init() }
func file_proto_namenode_namenode_proto_init() {
	if File_proto_namenode_namenode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_namenode_namenode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLeaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataNodeMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataNodeMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDataNodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDataNodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_namenode_namenode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namenode_namenode_proto_goTypes,
		DependencyIndexes: file_proto_namenode_namenode_proto_depIdxs,
		MessageInfos:      file_proto_namenode_namenode_proto_msgTypes,
	}.Build()
	File_proto_namenode_namenode_proto = out.File
	file_proto_namenode_namenode_proto_rawDesc = nil
	file_proto_namenode_namenode_proto_goTypes = nil
	file_proto_namenode_namenode_proto_depIdxs = nil
}
